#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Fri Jun 19 04:15:52 UTC 2020
# SW Build 2579327 on Sat Jun 29 14:34:41 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xvlog --incr --relax -L axi_vip_v1_1_5 -L xilinx_vip -prj GACTX_bank3_tb_vlog.prj"
xvlog --incr --relax -L axi_vip_v1_1_5 -L xilinx_vip -prj GACTX_bank3_tb_vlog.prj 2>&1 | tee compile.log

