webtalk_init -webtalk_dir /home/nimbix/workspace/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-06-19 04:27:54" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDx v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDx" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c3a053ho7aggci046daigtsuk8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2297.590 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "68.719 GB" -context "user_environment"
webtalk_register_client -client sdx
webtalk_add_data -client sdx -key uid -value "NA" -context "sdx\\\\tool/1592540874829"
webtalk_add_data -client sdx -key RecordType -value "ToolUsage" -context "sdx\\\\tool/1592540874829"
webtalk_add_data -client sdx -key BOOTGEN_count -value "0" -context "sdx\\\\tool/1592540874829"
webtalk_add_data -client sdx -key FLASH_count -value "0" -context "sdx\\\\tool/1592540874829"
webtalk_add_data -client sdx -key MOVE_APP_TO_SYSTEM_count -value "0" -context "sdx\\\\tool/1592540874829"
webtalk_add_data -client sdx -key SDX_EXPORT_count -value "0" -context "sdx\\\\tool/1592540874829"
webtalk_add_data -client sdx -key SDX_IMPORT_count -value "0" -context "sdx\\\\tool/1592540874829"
webtalk_add_data -client sdx -key SDX_BUILD_count -value "1" -context "sdx\\\\tool/1592540874829"
webtalk_add_data -client sdx -key SDX_NO_OP_BUILD_count -value "1" -context "sdx\\\\tool/1592540874829"
webtalk_add_data -client sdx -key TCF_APP_DEBUG_count -value "0" -context "sdx\\\\tool/1592540874829"
webtalk_add_data -client sdx -key TCF_SYSTEM_DEBUG_count -value "0" -context "sdx\\\\tool/1592540874829"
webtalk_add_data -client sdx -key GDB_DEBUG_count -value "0" -context "sdx\\\\tool/1592540874829"
webtalk_add_data -client sdx -key QEMU_DEBUG_count -value "0" -context "sdx\\\\tool/1592540874829"
webtalk_add_data -client sdx -key ESTIMATION_DEBUG_count -value "0" -context "sdx\\\\tool/1592540874829"
webtalk_add_data -client sdx -key SDSOC_TRACE_count -value "0" -context "sdx\\\\tool/1592540874829"
webtalk_add_data -client sdx -key PERFORMANCE_ANALYSIS_count -value "0" -context "sdx\\\\tool/1592540874829"
webtalk_add_data -client sdx -key SPM_ANALYSIS_count -value "0" -context "sdx\\\\tool/1592540874829"
webtalk_add_data -client sdx -key CROSS_TRIGGER_count -value "0" -context "sdx\\\\tool/1592540874829"
webtalk_add_data -client sdx -key TCF_PROFILER_count -value "0" -context "sdx\\\\tool/1592540874829"
webtalk_add_data -client sdx -key APPLICATION_PLATFORM_CHANGE_count -value "0" -context "sdx\\\\tool/1592540874829"
webtalk_add_data -client sdx -key APPLICATION_SYS_CONFIG_CHANGE_count -value "0" -context "sdx\\\\tool/1592540874829"
webtalk_add_data -client sdx -key SYSTEM_PLATFORM_CHANGE_count -value "0" -context "sdx\\\\tool/1592540874829"
webtalk_transmit -clientid 1490333344 -regid "" -xml /home/nimbix/workspace/webtalk/usage_statistics_ext_sdx.xml -html /home/nimbix/workspace/webtalk/usage_statistics_ext_sdx.html -wdm /home/nimbix/workspace/webtalk/sdx_webtalk.wdm -intro "<H3>SDx Usage Report</H3><BR>"
webtalk_terminate
